Ft home page development
BaSD-2021/David-MindSet-server pull request #21
Opened 2021-11-18 01:57 UTC by sofpag

Mi recurso (companies) está de ejemplo

2021-11-18 03:34 UTC, Pablo-Balbo requested changes

2021-11-18 03:34 UTC, Pablo-Balbo commented on public/styles/reset.css
> +*/
We should delete this lines.

2021-11-18 13:54 UTC, sofpag commented on public/styles/reset.css
> +*/
No es necesario. Es la información del código que estamos usando (que tomamos de internet)

2021-11-18 22:01 UTC, julianv97 approved these changes

2021-11-19 13:47 UTC, agustin-schiaffino approved these changes

2021-11-19 19:35 UTC, closed without merging