Ft applications views
BaSD-2021/David-MindSet-server pull request #34
Opened 2021-11-21 21:08 UTC by GuidoGlielmi

Merge of ft-applications-views to development

2021-11-23 13:23 UTC, davidcurras approved these changes

2021-11-23 14:27 UTC, AndresCespedes23 requested changes

2021-11-23 14:27 UTC, AndresCespedes23 commented on public/js/applications/form-applications.js
> +    )}` /* `https://basd-2021-david-mindset-dev.herokuapp.com/api/applications/${params.get('id')}` */,
Hola Guido, la url de los fetchs hay que poner la de Heroku y hacer esa correccion que dijo David del window.location.origin

2021-11-23 14:27 UTC, AndresCespedes23 commented on public/js/applications/list-applications.js
> +    window.location.href = `http://localhost:8000/api/views/applications/form-applications.html?id=${application._id}` /* `${window.location.origin}/public/views/applications/form-applications.html?_
Hola Guido, en este archivo hay que hacer lo mismo que te comente en el archivo anterior

2021-11-23 14:27 UTC, AndresCespedes23 commented on index.js
> +//require('dotenv').config();
Hola Guido, tenes que hacer los cambios para que se pueda deployar en Heroku

2021-11-24 01:28 UTC, valeferaudo commented on public/index.html
> +      <a href="views/applications/list-applications.html" class="user">Applications</a>
Aca cambia list-applications por listAplication

2021-11-24 01:29 UTC, valeferaudo approved these changes

2021-11-24 02:03 UTC, AndresCespedes23 approved these changes

2021-11-24 02:03 UTC, merged